<?php
/**
 * TransactionsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Puntjes
 *
 * Puntjes Loyalty API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Puntjes\Spike\Oag\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Puntjes\Spike\Oag\ApiException;
use Puntjes\Spike\Oag\Configuration;
use Puntjes\Spike\Oag\DebugPlugin;
use Puntjes\Spike\Oag\HeaderSelector;
use Puntjes\Spike\Oag\FormDataProcessor;
use Puntjes\Spike\Oag\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * TransactionsApi Class Doc Comment
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('https://puntjes.app/api/v1');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listCustomerTransactions
     *
     * @param  string $customer customer (required)
     * @param  string $date_from date_from (optional)
     * @param  string $date_to date_to (optional)
     * @param  int $page page (optional, default to 1)
     *
     * @throws \Puntjes\Spike\Oag\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Puntjes\Spike\Oag\Model\ListCustomerTransactions200Response|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse
     */
    public function listCustomerTransactions($customer, $date_from = null, $date_to = null, $page = 1)
    {
        list($response) = $this->listCustomerTransactionsWithHttpInfo($customer, $date_from, $date_to, $page);
        return $response;
    }

    /**
     * Operation listCustomerTransactionsWithHttpInfo
     *
     * @param  string $customer (required)
     * @param  string $date_from (optional)
     * @param  string $date_to (optional)
     * @param  int $page (optional, default to 1)
     *
     * @throws \Puntjes\Spike\Oag\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Puntjes\Spike\Oag\Model\ListCustomerTransactions200Response|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listCustomerTransactionsWithHttpInfo($customer, $date_from = null, $date_to = null, $page = 1)
    {
        $request = $this->listCustomerTransactionsRequest($customer, $date_from, $date_to, $page);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ListCustomerTransactions200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\Puntjes\Spike\Oag\Model\ListCustomerTransactions200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ListCustomerTransactions200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listCustomerTransactionsAsync
     *
     * @param  string $customer (required)
     * @param  string $date_from (optional)
     * @param  string $date_to (optional)
     * @param  int $page (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function listCustomerTransactionsAsync($customer, $date_from = null, $date_to = null, $page = 1)
    {
        return $this->listCustomerTransactionsAsyncWithHttpInfo($customer, $date_from, $date_to, $page)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listCustomerTransactionsAsyncWithHttpInfo
     *
     * @param  string $customer (required)
     * @param  string $date_from (optional)
     * @param  string $date_to (optional)
     * @param  int $page (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function listCustomerTransactionsAsyncWithHttpInfo($customer, $date_from = null, $date_to = null, $page = 1)
    {
        $returnType = '\Puntjes\Spike\Oag\Model\ListCustomerTransactions200Response';
        $request = $this->listCustomerTransactionsRequest($customer, $date_from, $date_to, $page);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'listCustomerTransactions'
     *
     * @param  string $customer (required)
     * @param  string $date_from (optional)
     * @param  string $date_to (optional)
     * @param  int $page (optional, default to 1)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function listCustomerTransactionsRequest($customer, $date_from = null, $date_to = null, $page = 1)
    {
        // verify the required parameter 'customer' is set
        if ($customer === null || (is_array($customer) && count($customer) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer when calling listCustomerTransactions'
            );
        }
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling TransactionsApi.listCustomerTransactions, must be bigger than or equal to 1.');
        }


        $resourcePath = '/customers/{customer}/transactions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($date_from !== null) {
            if('form' === 'form' && is_array($date_from)) {
                foreach($date_from as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['date_from'] = $date_from;
            }
        }
        // query params
        if ($date_to !== null) {
            if('form' === 'form' && is_array($date_to)) {
                foreach($date_to as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['date_to'] = $date_to;
            }
        }
        // query params
        if ($page !== null) {
            if('form' === 'form' && is_array($page)) {
                foreach($page as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page'] = $page;
            }
        }


        // path params
        if ($customer !== null) {
            $resourcePath = str_replace(
                '{customer}',
                ObjectSerializer::toPathValue($customer),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation submitTransaction
     *
     * @param  \Puntjes\Spike\Oag\Model\CreateTransactionData $create_transaction_data create_transaction_data (required)
     *
     * @throws \Puntjes\Spike\Oag\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Puntjes\Spike\Oag\Model\SubmitTransaction201Response|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse
     */
    public function submitTransaction($create_transaction_data)
    {
        list($response) = $this->submitTransactionWithHttpInfo($create_transaction_data);
        return $response;
    }

    /**
     * Operation submitTransactionWithHttpInfo
     *
     * @param  \Puntjes\Spike\Oag\Model\CreateTransactionData $create_transaction_data (required)
     *
     * @throws \Puntjes\Spike\Oag\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Puntjes\Spike\Oag\Model\SubmitTransaction201Response|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse|\Puntjes\Spike\Oag\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function submitTransactionWithHttpInfo($create_transaction_data)
    {
        $request = $this->submitTransactionRequest($create_transaction_data);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\SubmitTransaction201Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 415:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\Puntjes\Spike\Oag\Model\SubmitTransaction201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\SubmitTransaction201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 415:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Puntjes\Spike\Oag\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation submitTransactionAsync
     *
     * @param  \Puntjes\Spike\Oag\Model\CreateTransactionData $create_transaction_data (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function submitTransactionAsync($create_transaction_data)
    {
        return $this->submitTransactionAsyncWithHttpInfo($create_transaction_data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation submitTransactionAsyncWithHttpInfo
     *
     * @param  \Puntjes\Spike\Oag\Model\CreateTransactionData $create_transaction_data (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function submitTransactionAsyncWithHttpInfo($create_transaction_data)
    {
        $returnType = '\Puntjes\Spike\Oag\Model\SubmitTransaction201Response';
        $request = $this->submitTransactionRequest($create_transaction_data);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'submitTransaction'
     *
     * @param  \Puntjes\Spike\Oag\Model\CreateTransactionData $create_transaction_data (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function submitTransactionRequest($create_transaction_data)
    {
        // verify the required parameter 'create_transaction_data' is set
        if ($create_transaction_data === null || (is_array($create_transaction_data) && count($create_transaction_data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_transaction_data when calling submitTransaction'
            );
        }

        $resourcePath = '/transactions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($create_transaction_data)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($create_transaction_data));
            } else {
                $httpBody = $create_transaction_data;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }


    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
