<?php
/**
 * CampaignListDataConfig
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Puntjes
 *
 * Puntjes Loyalty API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Puntjes\Spike\Oag\Model;

use \ArrayAccess;
use \Puntjes\Spike\Oag\ObjectSerializer;

/**
 * CampaignListDataConfig Class Doc Comment
 *
 * @category Class
 * @description Its &#x60;type&#x60; says which shape this is.
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CampaignListDataConfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CampaignListData_config';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'reward_type' => 'string',
        'scope' => 'string',
        'stackable' => 'bool',
        'points' => 'int',
        'max_points_per_purchase' => 'int',
        'products' => '\Puntjes\Spike\Oag\Model\CampaignProductRuleData[]',
        'branch_ids' => 'int[]',
        'type' => 'string',
        'gift' => '\Puntjes\Spike\Oag\Model\AnniversaryCampaignConfigDataGift',
        'every_n' => 'int',
        'min_amount' => 'int',
        'years' => 'int',
        'backfill' => 'bool',
        'months' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'reward_type' => null,
        'scope' => null,
        'stackable' => null,
        'points' => null,
        'max_points_per_purchase' => null,
        'products' => null,
        'branch_ids' => null,
        'type' => null,
        'gift' => null,
        'every_n' => null,
        'min_amount' => null,
        'years' => null,
        'backfill' => null,
        'months' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'reward_type' => false,
        'scope' => false,
        'stackable' => false,
        'points' => true,
        'max_points_per_purchase' => true,
        'products' => true,
        'branch_ids' => false,
        'type' => false,
        'gift' => false,
        'every_n' => false,
        'min_amount' => true,
        'years' => false,
        'backfill' => true,
        'months' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'reward_type' => 'reward_type',
        'scope' => 'scope',
        'stackable' => 'stackable',
        'points' => 'points',
        'max_points_per_purchase' => 'max_points_per_purchase',
        'products' => 'products',
        'branch_ids' => 'branch_ids',
        'type' => 'type',
        'gift' => 'gift',
        'every_n' => 'every_n',
        'min_amount' => 'min_amount',
        'years' => 'years',
        'backfill' => 'backfill',
        'months' => 'months'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'reward_type' => 'setRewardType',
        'scope' => 'setScope',
        'stackable' => 'setStackable',
        'points' => 'setPoints',
        'max_points_per_purchase' => 'setMaxPointsPerPurchase',
        'products' => 'setProducts',
        'branch_ids' => 'setBranchIds',
        'type' => 'setType',
        'gift' => 'setGift',
        'every_n' => 'setEveryN',
        'min_amount' => 'setMinAmount',
        'years' => 'setYears',
        'backfill' => 'setBackfill',
        'months' => 'setMonths'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'reward_type' => 'getRewardType',
        'scope' => 'getScope',
        'stackable' => 'getStackable',
        'points' => 'getPoints',
        'max_points_per_purchase' => 'getMaxPointsPerPurchase',
        'products' => 'getProducts',
        'branch_ids' => 'getBranchIds',
        'type' => 'getType',
        'gift' => 'getGift',
        'every_n' => 'getEveryN',
        'min_amount' => 'getMinAmount',
        'years' => 'getYears',
        'backfill' => 'getBackfill',
        'months' => 'getMonths'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const REWARD_TYPE_MULTIPLIER = 'multiplier';
    public const REWARD_TYPE_FIXED_POINTS = 'fixed_points';
    public const SCOPE_WHOLE = 'whole';
    public const SCOPE_WHOLE_PURCHASE = 'whole_purchase';
    public const SCOPE_PRODUCTS = 'products';
    public const TYPE_TRANSACTION = 'transaction';
    public const TYPE_MOMENT = 'moment';
    public const TYPE_NTH_PURCHASE = 'nth_purchase';
    public const TYPE_ANNIVERSARY = 'anniversary';
    public const TYPE_WIN_BACK = 'win_back';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRewardTypeAllowableValues()
    {
        return [
            self::REWARD_TYPE_MULTIPLIER,
            self::REWARD_TYPE_FIXED_POINTS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScopeAllowableValues()
    {
        return [
            self::SCOPE_WHOLE,
            self::SCOPE_WHOLE_PURCHASE,
            self::SCOPE_PRODUCTS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_TRANSACTION,
            self::TYPE_MOMENT,
            self::TYPE_NTH_PURCHASE,
            self::TYPE_ANNIVERSARY,
            self::TYPE_WIN_BACK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('reward_type', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('stackable', $data ?? [], null);
        $this->setIfExists('points', $data ?? [], null);
        $this->setIfExists('max_points_per_purchase', $data ?? [], null);
        $this->setIfExists('products', $data ?? [], null);
        $this->setIfExists('branch_ids', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('gift', $data ?? [], null);
        $this->setIfExists('every_n', $data ?? [], null);
        $this->setIfExists('min_amount', $data ?? [], null);
        $this->setIfExists('years', $data ?? [], null);
        $this->setIfExists('backfill', $data ?? [], null);
        $this->setIfExists('months', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getRewardTypeAllowableValues();
        if (!is_null($this->container['reward_type']) && !in_array($this->container['reward_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'reward_type', must be one of '%s'",
                $this->container['reward_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getScopeAllowableValues();
        if (!is_null($this->container['scope']) && !in_array($this->container['scope'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'scope', must be one of '%s'",
                $this->container['scope'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['gift'] === null) {
            $invalidProperties[] = "'gift' can't be null";
        }
        if ($this->container['every_n'] === null) {
            $invalidProperties[] = "'every_n' can't be null";
        }
        if ($this->container['years'] === null) {
            $invalidProperties[] = "'years' can't be null";
        }
        if ($this->container['months'] === null) {
            $invalidProperties[] = "'months' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets reward_type
     *
     * @return string|null
     */
    public function getRewardType()
    {
        return $this->container['reward_type'];
    }

    /**
     * Sets reward_type
     *
     * @param string|null $reward_type Multiply the points earned, or add a fixed number. Absent reads as `multiplier`.
     *
     * @return self
     */
    public function setRewardType($reward_type)
    {
        if (is_null($reward_type)) {
            throw new \InvalidArgumentException('non-nullable reward_type cannot be null');
        }
        $allowedValues = $this->getRewardTypeAllowableValues();
        if (!in_array($reward_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'reward_type', must be one of '%s'",
                    $reward_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['reward_type'] = $reward_type;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string|null
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string|null $scope `whole` and `whole_purchase` both mean the whole purchase. Absent reads as `whole`.
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }
        $allowedValues = $this->getScopeAllowableValues();
        if (!in_array($scope, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'scope', must be one of '%s'",
                    $scope,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets stackable
     *
     * @return bool|null
     */
    public function getStackable()
    {
        return $this->container['stackable'];
    }

    /**
     * Sets stackable
     *
     * @param bool|null $stackable Whether it pays out beside another campaign. Older rows carry `combineerbaar`.
     *
     * @return self
     */
    public function setStackable($stackable)
    {
        if (is_null($stackable)) {
            throw new \InvalidArgumentException('non-nullable stackable cannot be null');
        }
        $this->container['stackable'] = $stackable;

        return $this;
    }

    /**
     * Gets points
     *
     * @return int|null
     */
    public function getPoints()
    {
        return $this->container['points'];
    }

    /**
     * Sets points
     *
     * @param int|null $points The points added, when `reward_type` is `fixed_points`.
     *
     * @return self
     */
    public function setPoints($points)
    {
        if (is_null($points)) {
            array_push($this->openAPINullablesSetToNull, 'points');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('points', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['points'] = $points;

        return $this;
    }

    /**
     * Gets max_points_per_purchase
     *
     * @return int|null
     */
    public function getMaxPointsPerPurchase()
    {
        return $this->container['max_points_per_purchase'];
    }

    /**
     * Sets max_points_per_purchase
     *
     * @param int|null $max_points_per_purchase The most this campaign pays out on one purchase.
     *
     * @return self
     */
    public function setMaxPointsPerPurchase($max_points_per_purchase)
    {
        if (is_null($max_points_per_purchase)) {
            array_push($this->openAPINullablesSetToNull, 'max_points_per_purchase');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_points_per_purchase', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_points_per_purchase'] = $max_points_per_purchase;

        return $this;
    }

    /**
     * Gets products
     *
     * @return \Puntjes\Spike\Oag\Model\CampaignProductRuleData[]|null
     */
    public function getProducts()
    {
        return $this->container['products'];
    }

    /**
     * Sets products
     *
     * @param \Puntjes\Spike\Oag\Model\CampaignProductRuleData[]|null $products The products the campaign is limited to, when `scope` is `products`.
     *
     * @return self
     */
    public function setProducts($products)
    {
        if (is_null($products)) {
            array_push($this->openAPINullablesSetToNull, 'products');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('products', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['products'] = $products;

        return $this;
    }

    /**
     * Gets branch_ids
     *
     * @return int[]|null
     */
    public function getBranchIds()
    {
        return $this->container['branch_ids'];
    }

    /**
     * Sets branch_ids
     *
     * @param int[]|null $branch_ids The branches this campaign runs in. Absent or empty means all of them.
     *
     * @return self
     */
    public function setBranchIds($branch_ids)
    {
        if (is_null($branch_ids)) {
            throw new \InvalidArgumentException('non-nullable branch_ids cannot be null');
        }
        $this->container['branch_ids'] = $branch_ids;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Which shape this is.
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets gift
     *
     * @return \Puntjes\Spike\Oag\Model\AnniversaryCampaignConfigDataGift
     */
    public function getGift()
    {
        return $this->container['gift'];
    }

    /**
     * Sets gift
     *
     * @param \Puntjes\Spike\Oag\Model\AnniversaryCampaignConfigDataGift $gift gift
     *
     * @return self
     */
    public function setGift($gift)
    {
        if (is_null($gift)) {
            throw new \InvalidArgumentException('non-nullable gift cannot be null');
        }
        $this->container['gift'] = $gift;

        return $this;
    }

    /**
     * Gets every_n
     *
     * @return int
     */
    public function getEveryN()
    {
        return $this->container['every_n'];
    }

    /**
     * Sets every_n
     *
     * @param int $every_n Which purchase triggers the gift. 3 means every third one.
     *
     * @return self
     */
    public function setEveryN($every_n)
    {
        if (is_null($every_n)) {
            throw new \InvalidArgumentException('non-nullable every_n cannot be null');
        }
        $this->container['every_n'] = $every_n;

        return $this;
    }

    /**
     * Gets min_amount
     *
     * @return int|null
     */
    public function getMinAmount()
    {
        return $this->container['min_amount'];
    }

    /**
     * Sets min_amount
     *
     * @param int|null $min_amount The smallest purchase that counts, in cents.
     *
     * @return self
     */
    public function setMinAmount($min_amount)
    {
        if (is_null($min_amount)) {
            array_push($this->openAPINullablesSetToNull, 'min_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('min_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['min_amount'] = $min_amount;

        return $this;
    }

    /**
     * Gets years
     *
     * @return int
     */
    public function getYears()
    {
        return $this->container['years'];
    }

    /**
     * Sets years
     *
     * @param int $years How many years after joining the gift is sent.
     *
     * @return self
     */
    public function setYears($years)
    {
        if (is_null($years)) {
            throw new \InvalidArgumentException('non-nullable years cannot be null');
        }
        $this->container['years'] = $years;

        return $this;
    }

    /**
     * Gets backfill
     *
     * @return bool|null
     */
    public function getBackfill()
    {
        return $this->container['backfill'];
    }

    /**
     * Sets backfill
     *
     * @param bool|null $backfill Whether customers who passed the mark before the campaign started also get it.
     *
     * @return self
     */
    public function setBackfill($backfill)
    {
        if (is_null($backfill)) {
            array_push($this->openAPINullablesSetToNull, 'backfill');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('backfill', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['backfill'] = $backfill;

        return $this;
    }

    /**
     * Gets months
     *
     * @return int
     */
    public function getMonths()
    {
        return $this->container['months'];
    }

    /**
     * Sets months
     *
     * @param int $months How many months without a purchase before the gift is sent.
     *
     * @return self
     */
    public function setMonths($months)
    {
        if (is_null($months)) {
            throw new \InvalidArgumentException('non-nullable months cannot be null');
        }
        $this->container['months'] = $months;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


