<?php
/**
 * CommerceStatisticsData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Puntjes
 *
 * Puntjes Loyalty API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Puntjes\Spike\Oag\Model;

use \ArrayAccess;
use \Puntjes\Spike\Oag\ObjectSerializer;

/**
 * CommerceStatisticsData Class Doc Comment
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CommerceStatisticsData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CommerceStatisticsData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'orders' => 'int',
        'revenue_cents' => 'int',
        'average_order_value_cents' => 'int',
        'itemized' => '\Puntjes\Spike\Oag\Model\ItemizedStatisticsData',
        'volume_trend' => '\Puntjes\Spike\Oag\Model\VolumeBucketData[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'orders' => null,
        'revenue_cents' => null,
        'average_order_value_cents' => null,
        'itemized' => null,
        'volume_trend' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'orders' => false,
        'revenue_cents' => false,
        'average_order_value_cents' => false,
        'itemized' => false,
        'volume_trend' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'orders' => 'orders',
        'revenue_cents' => 'revenue_cents',
        'average_order_value_cents' => 'average_order_value_cents',
        'itemized' => 'itemized',
        'volume_trend' => 'volume_trend'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'orders' => 'setOrders',
        'revenue_cents' => 'setRevenueCents',
        'average_order_value_cents' => 'setAverageOrderValueCents',
        'itemized' => 'setItemized',
        'volume_trend' => 'setVolumeTrend'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'orders' => 'getOrders',
        'revenue_cents' => 'getRevenueCents',
        'average_order_value_cents' => 'getAverageOrderValueCents',
        'itemized' => 'getItemized',
        'volume_trend' => 'getVolumeTrend'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('orders', $data ?? [], null);
        $this->setIfExists('revenue_cents', $data ?? [], null);
        $this->setIfExists('average_order_value_cents', $data ?? [], null);
        $this->setIfExists('itemized', $data ?? [], null);
        $this->setIfExists('volume_trend', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['orders'] === null) {
            $invalidProperties[] = "'orders' can't be null";
        }
        if ($this->container['revenue_cents'] === null) {
            $invalidProperties[] = "'revenue_cents' can't be null";
        }
        if ($this->container['average_order_value_cents'] === null) {
            $invalidProperties[] = "'average_order_value_cents' can't be null";
        }
        if ($this->container['itemized'] === null) {
            $invalidProperties[] = "'itemized' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets orders
     *
     * @return int
     */
    public function getOrders()
    {
        return $this->container['orders'];
    }

    /**
     * Sets orders
     *
     * @param int $orders orders
     *
     * @return self
     */
    public function setOrders($orders)
    {
        if (is_null($orders)) {
            throw new \InvalidArgumentException('non-nullable orders cannot be null');
        }
        $this->container['orders'] = $orders;

        return $this;
    }

    /**
     * Gets revenue_cents
     *
     * @return int
     */
    public function getRevenueCents()
    {
        return $this->container['revenue_cents'];
    }

    /**
     * Sets revenue_cents
     *
     * @param int $revenue_cents revenue_cents
     *
     * @return self
     */
    public function setRevenueCents($revenue_cents)
    {
        if (is_null($revenue_cents)) {
            throw new \InvalidArgumentException('non-nullable revenue_cents cannot be null');
        }
        $this->container['revenue_cents'] = $revenue_cents;

        return $this;
    }

    /**
     * Gets average_order_value_cents
     *
     * @return int
     */
    public function getAverageOrderValueCents()
    {
        return $this->container['average_order_value_cents'];
    }

    /**
     * Sets average_order_value_cents
     *
     * @param int $average_order_value_cents average_order_value_cents
     *
     * @return self
     */
    public function setAverageOrderValueCents($average_order_value_cents)
    {
        if (is_null($average_order_value_cents)) {
            throw new \InvalidArgumentException('non-nullable average_order_value_cents cannot be null');
        }
        $this->container['average_order_value_cents'] = $average_order_value_cents;

        return $this;
    }

    /**
     * Gets itemized
     *
     * @return \Puntjes\Spike\Oag\Model\ItemizedStatisticsData
     */
    public function getItemized()
    {
        return $this->container['itemized'];
    }

    /**
     * Sets itemized
     *
     * @param \Puntjes\Spike\Oag\Model\ItemizedStatisticsData $itemized itemized
     *
     * @return self
     */
    public function setItemized($itemized)
    {
        if (is_null($itemized)) {
            throw new \InvalidArgumentException('non-nullable itemized cannot be null');
        }
        $this->container['itemized'] = $itemized;

        return $this;
    }

    /**
     * Gets volume_trend
     *
     * @return \Puntjes\Spike\Oag\Model\VolumeBucketData[]|null
     */
    public function getVolumeTrend()
    {
        return $this->container['volume_trend'];
    }

    /**
     * Sets volume_trend
     *
     * @param \Puntjes\Spike\Oag\Model\VolumeBucketData[]|null $volume_trend volume_trend
     *
     * @return self
     */
    public function setVolumeTrend($volume_trend)
    {
        if (is_null($volume_trend)) {
            throw new \InvalidArgumentException('non-nullable volume_trend cannot be null');
        }
        $this->container['volume_trend'] = $volume_trend;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


