<?php
/**
 * CustomerData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Puntjes
 *
 * Puntjes Loyalty API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Puntjes\Spike\Oag\Model;

use \ArrayAccess;
use \Puntjes\Spike\Oag\ObjectSerializer;

/**
 * CustomerData Class Doc Comment
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CustomerData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CustomerData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'first_name' => 'string',
        'last_name' => 'string',
        'email' => 'string',
        'phone' => 'string',
        'external_id' => 'string',
        'date_of_birth' => 'string',
        'customer_since' => 'string',
        'locale' => 'string',
        'status' => '\Puntjes\Spike\Oag\Model\CustomerStatusData',
        'identifiers' => '\Puntjes\Spike\Oag\Model\CustomerIdentifierData[]',
        'marketing_consent' => 'bool',
        'marketing_consent_granted_at' => 'string',
        'marketing_consent_granted_source' => 'string',
        'marketing_consent_withdrawn_at' => 'string',
        'marketing_consent_withdrawn_source' => 'string',
        'marketing_consent_statement_version' => 'string',
        'marketing_consent_recorded_by' => 'string',
        'marketing_consent_recorded_by_client_id' => 'string',
        'loyalty_card_code' => 'string',
        'deactivated_at' => 'string',
        'anonymized_at' => 'string',
        'created_at' => 'string',
        'updated_at' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'first_name' => null,
        'last_name' => null,
        'email' => null,
        'phone' => null,
        'external_id' => null,
        'date_of_birth' => null,
        'customer_since' => null,
        'locale' => null,
        'status' => null,
        'identifiers' => null,
        'marketing_consent' => null,
        'marketing_consent_granted_at' => null,
        'marketing_consent_granted_source' => null,
        'marketing_consent_withdrawn_at' => null,
        'marketing_consent_withdrawn_source' => null,
        'marketing_consent_statement_version' => null,
        'marketing_consent_recorded_by' => null,
        'marketing_consent_recorded_by_client_id' => null,
        'loyalty_card_code' => null,
        'deactivated_at' => null,
        'anonymized_at' => null,
        'created_at' => null,
        'updated_at' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'first_name' => true,
        'last_name' => true,
        'email' => true,
        'phone' => true,
        'external_id' => true,
        'date_of_birth' => true,
        'customer_since' => true,
        'locale' => true,
        'status' => false,
        'identifiers' => false,
        'marketing_consent' => false,
        'marketing_consent_granted_at' => true,
        'marketing_consent_granted_source' => true,
        'marketing_consent_withdrawn_at' => true,
        'marketing_consent_withdrawn_source' => true,
        'marketing_consent_statement_version' => true,
        'marketing_consent_recorded_by' => true,
        'marketing_consent_recorded_by_client_id' => true,
        'loyalty_card_code' => true,
        'deactivated_at' => true,
        'anonymized_at' => true,
        'created_at' => true,
        'updated_at' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'email' => 'email',
        'phone' => 'phone',
        'external_id' => 'external_id',
        'date_of_birth' => 'date_of_birth',
        'customer_since' => 'customer_since',
        'locale' => 'locale',
        'status' => 'status',
        'identifiers' => 'identifiers',
        'marketing_consent' => 'marketingConsent',
        'marketing_consent_granted_at' => 'marketingConsentGrantedAt',
        'marketing_consent_granted_source' => 'marketingConsentGrantedSource',
        'marketing_consent_withdrawn_at' => 'marketingConsentWithdrawnAt',
        'marketing_consent_withdrawn_source' => 'marketingConsentWithdrawnSource',
        'marketing_consent_statement_version' => 'marketingConsentStatementVersion',
        'marketing_consent_recorded_by' => 'marketingConsentRecordedBy',
        'marketing_consent_recorded_by_client_id' => 'marketingConsentRecordedByClientId',
        'loyalty_card_code' => 'loyalty_card_code',
        'deactivated_at' => 'deactivated_at',
        'anonymized_at' => 'anonymized_at',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'email' => 'setEmail',
        'phone' => 'setPhone',
        'external_id' => 'setExternalId',
        'date_of_birth' => 'setDateOfBirth',
        'customer_since' => 'setCustomerSince',
        'locale' => 'setLocale',
        'status' => 'setStatus',
        'identifiers' => 'setIdentifiers',
        'marketing_consent' => 'setMarketingConsent',
        'marketing_consent_granted_at' => 'setMarketingConsentGrantedAt',
        'marketing_consent_granted_source' => 'setMarketingConsentGrantedSource',
        'marketing_consent_withdrawn_at' => 'setMarketingConsentWithdrawnAt',
        'marketing_consent_withdrawn_source' => 'setMarketingConsentWithdrawnSource',
        'marketing_consent_statement_version' => 'setMarketingConsentStatementVersion',
        'marketing_consent_recorded_by' => 'setMarketingConsentRecordedBy',
        'marketing_consent_recorded_by_client_id' => 'setMarketingConsentRecordedByClientId',
        'loyalty_card_code' => 'setLoyaltyCardCode',
        'deactivated_at' => 'setDeactivatedAt',
        'anonymized_at' => 'setAnonymizedAt',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'email' => 'getEmail',
        'phone' => 'getPhone',
        'external_id' => 'getExternalId',
        'date_of_birth' => 'getDateOfBirth',
        'customer_since' => 'getCustomerSince',
        'locale' => 'getLocale',
        'status' => 'getStatus',
        'identifiers' => 'getIdentifiers',
        'marketing_consent' => 'getMarketingConsent',
        'marketing_consent_granted_at' => 'getMarketingConsentGrantedAt',
        'marketing_consent_granted_source' => 'getMarketingConsentGrantedSource',
        'marketing_consent_withdrawn_at' => 'getMarketingConsentWithdrawnAt',
        'marketing_consent_withdrawn_source' => 'getMarketingConsentWithdrawnSource',
        'marketing_consent_statement_version' => 'getMarketingConsentStatementVersion',
        'marketing_consent_recorded_by' => 'getMarketingConsentRecordedBy',
        'marketing_consent_recorded_by_client_id' => 'getMarketingConsentRecordedByClientId',
        'loyalty_card_code' => 'getLoyaltyCardCode',
        'deactivated_at' => 'getDeactivatedAt',
        'anonymized_at' => 'getAnonymizedAt',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('customer_since', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('identifiers', $data ?? [], null);
        $this->setIfExists('marketing_consent', $data ?? [], null);
        $this->setIfExists('marketing_consent_granted_at', $data ?? [], null);
        $this->setIfExists('marketing_consent_granted_source', $data ?? [], null);
        $this->setIfExists('marketing_consent_withdrawn_at', $data ?? [], null);
        $this->setIfExists('marketing_consent_withdrawn_source', $data ?? [], null);
        $this->setIfExists('marketing_consent_statement_version', $data ?? [], null);
        $this->setIfExists('marketing_consent_recorded_by', $data ?? [], null);
        $this->setIfExists('marketing_consent_recorded_by_client_id', $data ?? [], null);
        $this->setIfExists('loyalty_card_code', $data ?? [], null);
        $this->setIfExists('deactivated_at', $data ?? [], null);
        $this->setIfExists('anonymized_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['first_name'] === null && !$this->isNullableSetToNull('first_name')) {
            $invalidProperties[] = "'first_name' is required";
        }
        if ($this->container['last_name'] === null && !$this->isNullableSetToNull('last_name')) {
            $invalidProperties[] = "'last_name' is required";
        }
        if ($this->container['email'] === null && !$this->isNullableSetToNull('email')) {
            $invalidProperties[] = "'email' is required";
        }
        if ($this->container['phone'] === null && !$this->isNullableSetToNull('phone')) {
            $invalidProperties[] = "'phone' is required";
        }
        if ($this->container['external_id'] === null && !$this->isNullableSetToNull('external_id')) {
            $invalidProperties[] = "'external_id' is required";
        }
        if ($this->container['date_of_birth'] === null && !$this->isNullableSetToNull('date_of_birth')) {
            $invalidProperties[] = "'date_of_birth' is required";
        }
        if ($this->container['customer_since'] === null && !$this->isNullableSetToNull('customer_since')) {
            $invalidProperties[] = "'customer_since' is required";
        }
        if ($this->container['locale'] === null && !$this->isNullableSetToNull('locale')) {
            $invalidProperties[] = "'locale' is required";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['identifiers'] === null) {
            $invalidProperties[] = "'identifiers' can't be null";
        }
        if ($this->container['marketing_consent'] === null) {
            $invalidProperties[] = "'marketing_consent' can't be null";
        }
        if ($this->container['marketing_consent_granted_at'] === null && !$this->isNullableSetToNull('marketing_consent_granted_at')) {
            $invalidProperties[] = "'marketing_consent_granted_at' is required";
        }
        if ($this->container['marketing_consent_granted_source'] === null && !$this->isNullableSetToNull('marketing_consent_granted_source')) {
            $invalidProperties[] = "'marketing_consent_granted_source' is required";
        }
        if ($this->container['marketing_consent_withdrawn_at'] === null && !$this->isNullableSetToNull('marketing_consent_withdrawn_at')) {
            $invalidProperties[] = "'marketing_consent_withdrawn_at' is required";
        }
        if ($this->container['marketing_consent_withdrawn_source'] === null && !$this->isNullableSetToNull('marketing_consent_withdrawn_source')) {
            $invalidProperties[] = "'marketing_consent_withdrawn_source' is required";
        }
        if ($this->container['marketing_consent_statement_version'] === null && !$this->isNullableSetToNull('marketing_consent_statement_version')) {
            $invalidProperties[] = "'marketing_consent_statement_version' is required";
        }
        if ($this->container['marketing_consent_recorded_by'] === null && !$this->isNullableSetToNull('marketing_consent_recorded_by')) {
            $invalidProperties[] = "'marketing_consent_recorded_by' is required";
        }
        if ($this->container['marketing_consent_recorded_by_client_id'] === null && !$this->isNullableSetToNull('marketing_consent_recorded_by_client_id')) {
            $invalidProperties[] = "'marketing_consent_recorded_by_client_id' is required";
        }
        if ($this->container['loyalty_card_code'] === null && !$this->isNullableSetToNull('loyalty_card_code')) {
            $invalidProperties[] = "'loyalty_card_code' is required";
        }
        if ($this->container['deactivated_at'] === null && !$this->isNullableSetToNull('deactivated_at')) {
            $invalidProperties[] = "'deactivated_at' is required";
        }
        if ($this->container['anonymized_at'] === null && !$this->isNullableSetToNull('anonymized_at')) {
            $invalidProperties[] = "'anonymized_at' is required";
        }
        if ($this->container['created_at'] === null && !$this->isNullableSetToNull('created_at')) {
            $invalidProperties[] = "'created_at' is required";
        }
        if ($this->container['updated_at'] === null && !$this->isNullableSetToNull('updated_at')) {
            $invalidProperties[] = "'updated_at' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string|null $first_name first_name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            array_push($this->openAPINullablesSetToNull, 'first_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('first_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string|null $last_name last_name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            array_push($this->openAPINullablesSetToNull, 'last_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            array_push($this->openAPINullablesSetToNull, 'phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            array_push($this->openAPINullablesSetToNull, 'external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return string|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param string|null $date_of_birth date_of_birth
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_birth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_birth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets customer_since
     *
     * @return string|null
     */
    public function getCustomerSince()
    {
        return $this->container['customer_since'];
    }

    /**
     * Sets customer_since
     *
     * @param string|null $customer_since customer_since
     *
     * @return self
     */
    public function setCustomerSince($customer_since)
    {
        if (is_null($customer_since)) {
            array_push($this->openAPINullablesSetToNull, 'customer_since');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_since', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_since'] = $customer_since;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            array_push($this->openAPINullablesSetToNull, 'locale');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('locale', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Puntjes\Spike\Oag\Model\CustomerStatusData
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Puntjes\Spike\Oag\Model\CustomerStatusData $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets identifiers
     *
     * @return \Puntjes\Spike\Oag\Model\CustomerIdentifierData[]
     */
    public function getIdentifiers()
    {
        return $this->container['identifiers'];
    }

    /**
     * Sets identifiers
     *
     * @param \Puntjes\Spike\Oag\Model\CustomerIdentifierData[] $identifiers identifiers
     *
     * @return self
     */
    public function setIdentifiers($identifiers)
    {
        if (is_null($identifiers)) {
            throw new \InvalidArgumentException('non-nullable identifiers cannot be null');
        }
        $this->container['identifiers'] = $identifiers;

        return $this;
    }

    /**
     * Gets marketing_consent
     *
     * @return bool
     */
    public function getMarketingConsent()
    {
        return $this->container['marketing_consent'];
    }

    /**
     * Sets marketing_consent
     *
     * @param bool $marketing_consent marketing_consent
     *
     * @return self
     */
    public function setMarketingConsent($marketing_consent)
    {
        if (is_null($marketing_consent)) {
            throw new \InvalidArgumentException('non-nullable marketing_consent cannot be null');
        }
        $this->container['marketing_consent'] = $marketing_consent;

        return $this;
    }

    /**
     * Gets marketing_consent_granted_at
     *
     * @return string|null
     */
    public function getMarketingConsentGrantedAt()
    {
        return $this->container['marketing_consent_granted_at'];
    }

    /**
     * Sets marketing_consent_granted_at
     *
     * @param string|null $marketing_consent_granted_at marketing_consent_granted_at
     *
     * @return self
     */
    public function setMarketingConsentGrantedAt($marketing_consent_granted_at)
    {
        if (is_null($marketing_consent_granted_at)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_consent_granted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_consent_granted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_consent_granted_at'] = $marketing_consent_granted_at;

        return $this;
    }

    /**
     * Gets marketing_consent_granted_source
     *
     * @return string|null
     */
    public function getMarketingConsentGrantedSource()
    {
        return $this->container['marketing_consent_granted_source'];
    }

    /**
     * Sets marketing_consent_granted_source
     *
     * @param string|null $marketing_consent_granted_source marketing_consent_granted_source
     *
     * @return self
     */
    public function setMarketingConsentGrantedSource($marketing_consent_granted_source)
    {
        if (is_null($marketing_consent_granted_source)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_consent_granted_source');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_consent_granted_source', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_consent_granted_source'] = $marketing_consent_granted_source;

        return $this;
    }

    /**
     * Gets marketing_consent_withdrawn_at
     *
     * @return string|null
     */
    public function getMarketingConsentWithdrawnAt()
    {
        return $this->container['marketing_consent_withdrawn_at'];
    }

    /**
     * Sets marketing_consent_withdrawn_at
     *
     * @param string|null $marketing_consent_withdrawn_at marketing_consent_withdrawn_at
     *
     * @return self
     */
    public function setMarketingConsentWithdrawnAt($marketing_consent_withdrawn_at)
    {
        if (is_null($marketing_consent_withdrawn_at)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_consent_withdrawn_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_consent_withdrawn_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_consent_withdrawn_at'] = $marketing_consent_withdrawn_at;

        return $this;
    }

    /**
     * Gets marketing_consent_withdrawn_source
     *
     * @return string|null
     */
    public function getMarketingConsentWithdrawnSource()
    {
        return $this->container['marketing_consent_withdrawn_source'];
    }

    /**
     * Sets marketing_consent_withdrawn_source
     *
     * @param string|null $marketing_consent_withdrawn_source marketing_consent_withdrawn_source
     *
     * @return self
     */
    public function setMarketingConsentWithdrawnSource($marketing_consent_withdrawn_source)
    {
        if (is_null($marketing_consent_withdrawn_source)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_consent_withdrawn_source');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_consent_withdrawn_source', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_consent_withdrawn_source'] = $marketing_consent_withdrawn_source;

        return $this;
    }

    /**
     * Gets marketing_consent_statement_version
     *
     * @return string|null
     */
    public function getMarketingConsentStatementVersion()
    {
        return $this->container['marketing_consent_statement_version'];
    }

    /**
     * Sets marketing_consent_statement_version
     *
     * @param string|null $marketing_consent_statement_version marketing_consent_statement_version
     *
     * @return self
     */
    public function setMarketingConsentStatementVersion($marketing_consent_statement_version)
    {
        if (is_null($marketing_consent_statement_version)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_consent_statement_version');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_consent_statement_version', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_consent_statement_version'] = $marketing_consent_statement_version;

        return $this;
    }

    /**
     * Gets marketing_consent_recorded_by
     *
     * @return string|null
     */
    public function getMarketingConsentRecordedBy()
    {
        return $this->container['marketing_consent_recorded_by'];
    }

    /**
     * Sets marketing_consent_recorded_by
     *
     * @param string|null $marketing_consent_recorded_by marketing_consent_recorded_by
     *
     * @return self
     */
    public function setMarketingConsentRecordedBy($marketing_consent_recorded_by)
    {
        if (is_null($marketing_consent_recorded_by)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_consent_recorded_by');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_consent_recorded_by', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_consent_recorded_by'] = $marketing_consent_recorded_by;

        return $this;
    }

    /**
     * Gets marketing_consent_recorded_by_client_id
     *
     * @return string|null
     */
    public function getMarketingConsentRecordedByClientId()
    {
        return $this->container['marketing_consent_recorded_by_client_id'];
    }

    /**
     * Sets marketing_consent_recorded_by_client_id
     *
     * @param string|null $marketing_consent_recorded_by_client_id marketing_consent_recorded_by_client_id
     *
     * @return self
     */
    public function setMarketingConsentRecordedByClientId($marketing_consent_recorded_by_client_id)
    {
        if (is_null($marketing_consent_recorded_by_client_id)) {
            array_push($this->openAPINullablesSetToNull, 'marketing_consent_recorded_by_client_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marketing_consent_recorded_by_client_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marketing_consent_recorded_by_client_id'] = $marketing_consent_recorded_by_client_id;

        return $this;
    }

    /**
     * Gets loyalty_card_code
     *
     * @return string|null
     */
    public function getLoyaltyCardCode()
    {
        return $this->container['loyalty_card_code'];
    }

    /**
     * Sets loyalty_card_code
     *
     * @param string|null $loyalty_card_code loyalty_card_code
     *
     * @return self
     */
    public function setLoyaltyCardCode($loyalty_card_code)
    {
        if (is_null($loyalty_card_code)) {
            array_push($this->openAPINullablesSetToNull, 'loyalty_card_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('loyalty_card_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['loyalty_card_code'] = $loyalty_card_code;

        return $this;
    }

    /**
     * Gets deactivated_at
     *
     * @return string|null
     */
    public function getDeactivatedAt()
    {
        return $this->container['deactivated_at'];
    }

    /**
     * Sets deactivated_at
     *
     * @param string|null $deactivated_at deactivated_at
     *
     * @return self
     */
    public function setDeactivatedAt($deactivated_at)
    {
        if (is_null($deactivated_at)) {
            array_push($this->openAPINullablesSetToNull, 'deactivated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deactivated_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deactivated_at'] = $deactivated_at;

        return $this;
    }

    /**
     * Gets anonymized_at
     *
     * @return string|null
     */
    public function getAnonymizedAt()
    {
        return $this->container['anonymized_at'];
    }

    /**
     * Sets anonymized_at
     *
     * @param string|null $anonymized_at anonymized_at
     *
     * @return self
     */
    public function setAnonymizedAt($anonymized_at)
    {
        if (is_null($anonymized_at)) {
            array_push($this->openAPINullablesSetToNull, 'anonymized_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('anonymized_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['anonymized_at'] = $anonymized_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            array_push($this->openAPINullablesSetToNull, 'created_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            array_push($this->openAPINullablesSetToNull, 'updated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updated_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


