<?php
/**
 * LoyaltyStatisticsData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Puntjes
 *
 * Puntjes Loyalty API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Puntjes\Spike\Oag\Model;

use \ArrayAccess;
use \Puntjes\Spike\Oag\ObjectSerializer;

/**
 * LoyaltyStatisticsData Class Doc Comment
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LoyaltyStatisticsData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LoyaltyStatisticsData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'points_issued' => 'int',
        'points_redeemed' => 'int',
        'points_expired' => 'int',
        'net_adjustments' => 'int',
        'redemption_rate' => 'float',
        'breakage_rate' => 'float',
        'points_redeemed_from_import' => 'int',
        'points_expired_from_import' => 'int',
        'redemption_rate_excluding_import' => 'float',
        'breakage_rate_excluding_import' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'points_issued' => null,
        'points_redeemed' => null,
        'points_expired' => null,
        'net_adjustments' => null,
        'redemption_rate' => null,
        'breakage_rate' => null,
        'points_redeemed_from_import' => null,
        'points_expired_from_import' => null,
        'redemption_rate_excluding_import' => null,
        'breakage_rate_excluding_import' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'points_issued' => false,
        'points_redeemed' => false,
        'points_expired' => false,
        'net_adjustments' => false,
        'redemption_rate' => true,
        'breakage_rate' => true,
        'points_redeemed_from_import' => false,
        'points_expired_from_import' => false,
        'redemption_rate_excluding_import' => true,
        'breakage_rate_excluding_import' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'points_issued' => 'points_issued',
        'points_redeemed' => 'points_redeemed',
        'points_expired' => 'points_expired',
        'net_adjustments' => 'net_adjustments',
        'redemption_rate' => 'redemption_rate',
        'breakage_rate' => 'breakage_rate',
        'points_redeemed_from_import' => 'points_redeemed_from_import',
        'points_expired_from_import' => 'points_expired_from_import',
        'redemption_rate_excluding_import' => 'redemption_rate_excluding_import',
        'breakage_rate_excluding_import' => 'breakage_rate_excluding_import'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'points_issued' => 'setPointsIssued',
        'points_redeemed' => 'setPointsRedeemed',
        'points_expired' => 'setPointsExpired',
        'net_adjustments' => 'setNetAdjustments',
        'redemption_rate' => 'setRedemptionRate',
        'breakage_rate' => 'setBreakageRate',
        'points_redeemed_from_import' => 'setPointsRedeemedFromImport',
        'points_expired_from_import' => 'setPointsExpiredFromImport',
        'redemption_rate_excluding_import' => 'setRedemptionRateExcludingImport',
        'breakage_rate_excluding_import' => 'setBreakageRateExcludingImport'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'points_issued' => 'getPointsIssued',
        'points_redeemed' => 'getPointsRedeemed',
        'points_expired' => 'getPointsExpired',
        'net_adjustments' => 'getNetAdjustments',
        'redemption_rate' => 'getRedemptionRate',
        'breakage_rate' => 'getBreakageRate',
        'points_redeemed_from_import' => 'getPointsRedeemedFromImport',
        'points_expired_from_import' => 'getPointsExpiredFromImport',
        'redemption_rate_excluding_import' => 'getRedemptionRateExcludingImport',
        'breakage_rate_excluding_import' => 'getBreakageRateExcludingImport'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('points_issued', $data ?? [], null);
        $this->setIfExists('points_redeemed', $data ?? [], null);
        $this->setIfExists('points_expired', $data ?? [], null);
        $this->setIfExists('net_adjustments', $data ?? [], null);
        $this->setIfExists('redemption_rate', $data ?? [], null);
        $this->setIfExists('breakage_rate', $data ?? [], null);
        $this->setIfExists('points_redeemed_from_import', $data ?? [], null);
        $this->setIfExists('points_expired_from_import', $data ?? [], null);
        $this->setIfExists('redemption_rate_excluding_import', $data ?? [], null);
        $this->setIfExists('breakage_rate_excluding_import', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets points_issued
     *
     * @return int|null
     */
    public function getPointsIssued()
    {
        return $this->container['points_issued'];
    }

    /**
     * Sets points_issued
     *
     * @param int|null $points_issued points_issued
     *
     * @return self
     */
    public function setPointsIssued($points_issued)
    {
        if (is_null($points_issued)) {
            throw new \InvalidArgumentException('non-nullable points_issued cannot be null');
        }
        $this->container['points_issued'] = $points_issued;

        return $this;
    }

    /**
     * Gets points_redeemed
     *
     * @return int|null
     */
    public function getPointsRedeemed()
    {
        return $this->container['points_redeemed'];
    }

    /**
     * Sets points_redeemed
     *
     * @param int|null $points_redeemed Points spent on rewards in the period, including points customers brought along from another loyalty system.
     *
     * @return self
     */
    public function setPointsRedeemed($points_redeemed)
    {
        if (is_null($points_redeemed)) {
            throw new \InvalidArgumentException('non-nullable points_redeemed cannot be null');
        }
        $this->container['points_redeemed'] = $points_redeemed;

        return $this;
    }

    /**
     * Gets points_expired
     *
     * @return int|null
     */
    public function getPointsExpired()
    {
        return $this->container['points_expired'];
    }

    /**
     * Sets points_expired
     *
     * @param int|null $points_expired Points that expired in the period, including points customers brought along from another loyalty system.
     *
     * @return self
     */
    public function setPointsExpired($points_expired)
    {
        if (is_null($points_expired)) {
            throw new \InvalidArgumentException('non-nullable points_expired cannot be null');
        }
        $this->container['points_expired'] = $points_expired;

        return $this;
    }

    /**
     * Gets net_adjustments
     *
     * @return int|null
     */
    public function getNetAdjustments()
    {
        return $this->container['net_adjustments'];
    }

    /**
     * Sets net_adjustments
     *
     * @param int|null $net_adjustments net_adjustments
     *
     * @return self
     */
    public function setNetAdjustments($net_adjustments)
    {
        if (is_null($net_adjustments)) {
            throw new \InvalidArgumentException('non-nullable net_adjustments cannot be null');
        }
        $this->container['net_adjustments'] = $net_adjustments;

        return $this;
    }

    /**
     * Gets redemption_rate
     *
     * @return float|null
     */
    public function getRedemptionRate()
    {
        return $this->container['redemption_rate'];
    }

    /**
     * Sets redemption_rate
     *
     * @param float|null $redemption_rate points_redeemed divided by points_issued, 3 decimals. Counts imported points when they are spent but not when they arrive, so it can pass 1.0 after an import. Use redemption_rate_excluding_import.
     *
     * @return self
     */
    public function setRedemptionRate($redemption_rate)
    {
        if (is_null($redemption_rate)) {
            array_push($this->openAPINullablesSetToNull, 'redemption_rate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redemption_rate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redemption_rate'] = $redemption_rate;

        return $this;
    }

    /**
     * Gets breakage_rate
     *
     * @return float|null
     */
    public function getBreakageRate()
    {
        return $this->container['breakage_rate'];
    }

    /**
     * Sets breakage_rate
     *
     * @param float|null $breakage_rate points_expired divided by points_issued, 4 decimals. Counts imported points when they expire but not when they arrive, so it can pass 1.0 after an import. Use breakage_rate_excluding_import.
     *
     * @return self
     */
    public function setBreakageRate($breakage_rate)
    {
        if (is_null($breakage_rate)) {
            array_push($this->openAPINullablesSetToNull, 'breakage_rate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('breakage_rate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['breakage_rate'] = $breakage_rate;

        return $this;
    }

    /**
     * Gets points_redeemed_from_import
     *
     * @return int|null
     */
    public function getPointsRedeemedFromImport()
    {
        return $this->container['points_redeemed_from_import'];
    }

    /**
     * Sets points_redeemed_from_import
     *
     * @param int|null $points_redeemed_from_import The part of points_redeemed that came from points customers brought along from another loyalty system.
     *
     * @return self
     */
    public function setPointsRedeemedFromImport($points_redeemed_from_import)
    {
        if (is_null($points_redeemed_from_import)) {
            throw new \InvalidArgumentException('non-nullable points_redeemed_from_import cannot be null');
        }
        $this->container['points_redeemed_from_import'] = $points_redeemed_from_import;

        return $this;
    }

    /**
     * Gets points_expired_from_import
     *
     * @return int|null
     */
    public function getPointsExpiredFromImport()
    {
        return $this->container['points_expired_from_import'];
    }

    /**
     * Sets points_expired_from_import
     *
     * @param int|null $points_expired_from_import The part of points_expired that came from points customers brought along from another loyalty system.
     *
     * @return self
     */
    public function setPointsExpiredFromImport($points_expired_from_import)
    {
        if (is_null($points_expired_from_import)) {
            throw new \InvalidArgumentException('non-nullable points_expired_from_import cannot be null');
        }
        $this->container['points_expired_from_import'] = $points_expired_from_import;

        return $this;
    }

    /**
     * Gets redemption_rate_excluding_import
     *
     * @return float|null
     */
    public function getRedemptionRateExcludingImport()
    {
        return $this->container['redemption_rate_excluding_import'];
    }

    /**
     * Sets redemption_rate_excluding_import
     *
     * @param float|null $redemption_rate_excluding_import Points redeemed minus points_redeemed_from_import, divided by points_issued, 3 decimals; null when nothing was issued. The rate the dashboard shows.
     *
     * @return self
     */
    public function setRedemptionRateExcludingImport($redemption_rate_excluding_import)
    {
        if (is_null($redemption_rate_excluding_import)) {
            array_push($this->openAPINullablesSetToNull, 'redemption_rate_excluding_import');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redemption_rate_excluding_import', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redemption_rate_excluding_import'] = $redemption_rate_excluding_import;

        return $this;
    }

    /**
     * Gets breakage_rate_excluding_import
     *
     * @return float|null
     */
    public function getBreakageRateExcludingImport()
    {
        return $this->container['breakage_rate_excluding_import'];
    }

    /**
     * Sets breakage_rate_excluding_import
     *
     * @param float|null $breakage_rate_excluding_import Points expired minus points_expired_from_import, divided by points_issued, 4 decimals; null when nothing was issued. The rate the dashboard shows.
     *
     * @return self
     */
    public function setBreakageRateExcludingImport($breakage_rate_excluding_import)
    {
        if (is_null($breakage_rate_excluding_import)) {
            array_push($this->openAPINullablesSetToNull, 'breakage_rate_excluding_import');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('breakage_rate_excluding_import', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['breakage_rate_excluding_import'] = $breakage_rate_excluding_import;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


