<?php
/**
 * RedemptionCreatedData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Puntjes
 *
 * Puntjes Loyalty API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Puntjes\Spike\Oag\Model;

use \ArrayAccess;
use \Puntjes\Spike\Oag\ObjectSerializer;

/**
 * RedemptionCreatedData Class Doc Comment
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RedemptionCreatedData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RedemptionCreatedData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'redemption_id' => 'int',
        'confirmation_code' => 'string',
        'reward' => '\Puntjes\Spike\Oag\Model\RedemptionRewardData',
        'points_deducted' => 'int',
        'remaining_balance' => 'int',
        'redeemed_at' => 'string',
        'expires_at' => 'string',
        'type_specific_data' => '\Puntjes\Spike\Oag\Model\RedemptionCreatedDataTypeSpecificData'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'redemption_id' => null,
        'confirmation_code' => null,
        'reward' => null,
        'points_deducted' => null,
        'remaining_balance' => null,
        'redeemed_at' => null,
        'expires_at' => null,
        'type_specific_data' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'redemption_id' => false,
        'confirmation_code' => false,
        'reward' => false,
        'points_deducted' => false,
        'remaining_balance' => false,
        'redeemed_at' => false,
        'expires_at' => true,
        'type_specific_data' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'redemption_id' => 'redemption_id',
        'confirmation_code' => 'confirmation_code',
        'reward' => 'reward',
        'points_deducted' => 'points_deducted',
        'remaining_balance' => 'remaining_balance',
        'redeemed_at' => 'redeemed_at',
        'expires_at' => 'expires_at',
        'type_specific_data' => 'type_specific_data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'redemption_id' => 'setRedemptionId',
        'confirmation_code' => 'setConfirmationCode',
        'reward' => 'setReward',
        'points_deducted' => 'setPointsDeducted',
        'remaining_balance' => 'setRemainingBalance',
        'redeemed_at' => 'setRedeemedAt',
        'expires_at' => 'setExpiresAt',
        'type_specific_data' => 'setTypeSpecificData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'redemption_id' => 'getRedemptionId',
        'confirmation_code' => 'getConfirmationCode',
        'reward' => 'getReward',
        'points_deducted' => 'getPointsDeducted',
        'remaining_balance' => 'getRemainingBalance',
        'redeemed_at' => 'getRedeemedAt',
        'expires_at' => 'getExpiresAt',
        'type_specific_data' => 'getTypeSpecificData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('redemption_id', $data ?? [], null);
        $this->setIfExists('confirmation_code', $data ?? [], null);
        $this->setIfExists('reward', $data ?? [], null);
        $this->setIfExists('points_deducted', $data ?? [], null);
        $this->setIfExists('remaining_balance', $data ?? [], null);
        $this->setIfExists('redeemed_at', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('type_specific_data', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['redemption_id'] === null) {
            $invalidProperties[] = "'redemption_id' can't be null";
        }
        if ($this->container['confirmation_code'] === null) {
            $invalidProperties[] = "'confirmation_code' can't be null";
        }
        if ($this->container['reward'] === null) {
            $invalidProperties[] = "'reward' can't be null";
        }
        if ($this->container['points_deducted'] === null) {
            $invalidProperties[] = "'points_deducted' can't be null";
        }
        if ($this->container['remaining_balance'] === null) {
            $invalidProperties[] = "'remaining_balance' can't be null";
        }
        if ($this->container['redeemed_at'] === null) {
            $invalidProperties[] = "'redeemed_at' can't be null";
        }
        if ($this->container['expires_at'] === null && !$this->isNullableSetToNull('expires_at')) {
            $invalidProperties[] = "'expires_at' is required";
        }
        if ($this->container['type_specific_data'] === null) {
            $invalidProperties[] = "'type_specific_data' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets redemption_id
     *
     * @return int
     */
    public function getRedemptionId()
    {
        return $this->container['redemption_id'];
    }

    /**
     * Sets redemption_id
     *
     * @param int $redemption_id redemption_id
     *
     * @return self
     */
    public function setRedemptionId($redemption_id)
    {
        if (is_null($redemption_id)) {
            throw new \InvalidArgumentException('non-nullable redemption_id cannot be null');
        }
        $this->container['redemption_id'] = $redemption_id;

        return $this;
    }

    /**
     * Gets confirmation_code
     *
     * @return string
     */
    public function getConfirmationCode()
    {
        return $this->container['confirmation_code'];
    }

    /**
     * Sets confirmation_code
     *
     * @param string $confirmation_code confirmation_code
     *
     * @return self
     */
    public function setConfirmationCode($confirmation_code)
    {
        if (is_null($confirmation_code)) {
            throw new \InvalidArgumentException('non-nullable confirmation_code cannot be null');
        }
        $this->container['confirmation_code'] = $confirmation_code;

        return $this;
    }

    /**
     * Gets reward
     *
     * @return \Puntjes\Spike\Oag\Model\RedemptionRewardData
     */
    public function getReward()
    {
        return $this->container['reward'];
    }

    /**
     * Sets reward
     *
     * @param \Puntjes\Spike\Oag\Model\RedemptionRewardData $reward reward
     *
     * @return self
     */
    public function setReward($reward)
    {
        if (is_null($reward)) {
            throw new \InvalidArgumentException('non-nullable reward cannot be null');
        }
        $this->container['reward'] = $reward;

        return $this;
    }

    /**
     * Gets points_deducted
     *
     * @return int
     */
    public function getPointsDeducted()
    {
        return $this->container['points_deducted'];
    }

    /**
     * Sets points_deducted
     *
     * @param int $points_deducted points_deducted
     *
     * @return self
     */
    public function setPointsDeducted($points_deducted)
    {
        if (is_null($points_deducted)) {
            throw new \InvalidArgumentException('non-nullable points_deducted cannot be null');
        }
        $this->container['points_deducted'] = $points_deducted;

        return $this;
    }

    /**
     * Gets remaining_balance
     *
     * @return int
     */
    public function getRemainingBalance()
    {
        return $this->container['remaining_balance'];
    }

    /**
     * Sets remaining_balance
     *
     * @param int $remaining_balance remaining_balance
     *
     * @return self
     */
    public function setRemainingBalance($remaining_balance)
    {
        if (is_null($remaining_balance)) {
            throw new \InvalidArgumentException('non-nullable remaining_balance cannot be null');
        }
        $this->container['remaining_balance'] = $remaining_balance;

        return $this;
    }

    /**
     * Gets redeemed_at
     *
     * @return string
     */
    public function getRedeemedAt()
    {
        return $this->container['redeemed_at'];
    }

    /**
     * Sets redeemed_at
     *
     * @param string $redeemed_at redeemed_at
     *
     * @return self
     */
    public function setRedeemedAt($redeemed_at)
    {
        if (is_null($redeemed_at)) {
            throw new \InvalidArgumentException('non-nullable redeemed_at cannot be null');
        }
        $this->container['redeemed_at'] = $redeemed_at;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return string|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param string|null $expires_at expires_at
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            array_push($this->openAPINullablesSetToNull, 'expires_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets type_specific_data
     *
     * @return \Puntjes\Spike\Oag\Model\RedemptionCreatedDataTypeSpecificData
     */
    public function getTypeSpecificData()
    {
        return $this->container['type_specific_data'];
    }

    /**
     * Sets type_specific_data
     *
     * @param \Puntjes\Spike\Oag\Model\RedemptionCreatedDataTypeSpecificData $type_specific_data type_specific_data
     *
     * @return self
     */
    public function setTypeSpecificData($type_specific_data)
    {
        if (is_null($type_specific_data)) {
            throw new \InvalidArgumentException('non-nullable type_specific_data cannot be null');
        }
        $this->container['type_specific_data'] = $type_specific_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


