<?php
/**
 * RewardCatalogItemData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Puntjes
 *
 * Puntjes Loyalty API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Puntjes\Spike\Oag\Model;

use \ArrayAccess;
use \Puntjes\Spike\Oag\ObjectSerializer;

/**
 * RewardCatalogItemData Class Doc Comment
 *
 * @category Class
 * @package  Puntjes\Spike\Oag
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RewardCatalogItemData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'RewardCatalogItemData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'name' => 'string',
        'description' => 'string',
        'type' => 'string',
        'point_cost' => 'int',
        'payment_amount' => 'int',
        'image_url' => 'string',
        'remaining_stock' => 'int',
        'total_stock' => 'int',
        'available_from' => 'string',
        'available_until' => 'string',
        'branches' => '\Puntjes\Spike\Oag\Model\BranchReferenceData[]',
        'product_reference' => 'string',
        'is_unlimited' => 'bool',
        'discount_type' => 'string',
        'discount_value' => 'int',
        'max_redemptions_per_customer' => 'int',
        'customer_redemptions' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'description' => null,
        'type' => null,
        'point_cost' => null,
        'payment_amount' => null,
        'image_url' => null,
        'remaining_stock' => null,
        'total_stock' => null,
        'available_from' => null,
        'available_until' => null,
        'branches' => null,
        'product_reference' => null,
        'is_unlimited' => null,
        'discount_type' => null,
        'discount_value' => null,
        'max_redemptions_per_customer' => null,
        'customer_redemptions' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'description' => true,
        'type' => false,
        'point_cost' => false,
        'payment_amount' => false,
        'image_url' => true,
        'remaining_stock' => true,
        'total_stock' => true,
        'available_from' => true,
        'available_until' => true,
        'branches' => true,
        'product_reference' => true,
        'is_unlimited' => false,
        'discount_type' => true,
        'discount_value' => true,
        'max_redemptions_per_customer' => true,
        'customer_redemptions' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'description' => 'description',
        'type' => 'type',
        'point_cost' => 'point_cost',
        'payment_amount' => 'payment_amount',
        'image_url' => 'image_url',
        'remaining_stock' => 'remaining_stock',
        'total_stock' => 'total_stock',
        'available_from' => 'available_from',
        'available_until' => 'available_until',
        'branches' => 'branches',
        'product_reference' => 'product_reference',
        'is_unlimited' => 'is_unlimited',
        'discount_type' => 'discount_type',
        'discount_value' => 'discount_value',
        'max_redemptions_per_customer' => 'max_redemptions_per_customer',
        'customer_redemptions' => 'customer_redemptions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'description' => 'setDescription',
        'type' => 'setType',
        'point_cost' => 'setPointCost',
        'payment_amount' => 'setPaymentAmount',
        'image_url' => 'setImageUrl',
        'remaining_stock' => 'setRemainingStock',
        'total_stock' => 'setTotalStock',
        'available_from' => 'setAvailableFrom',
        'available_until' => 'setAvailableUntil',
        'branches' => 'setBranches',
        'product_reference' => 'setProductReference',
        'is_unlimited' => 'setIsUnlimited',
        'discount_type' => 'setDiscountType',
        'discount_value' => 'setDiscountValue',
        'max_redemptions_per_customer' => 'setMaxRedemptionsPerCustomer',
        'customer_redemptions' => 'setCustomerRedemptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'description' => 'getDescription',
        'type' => 'getType',
        'point_cost' => 'getPointCost',
        'payment_amount' => 'getPaymentAmount',
        'image_url' => 'getImageUrl',
        'remaining_stock' => 'getRemainingStock',
        'total_stock' => 'getTotalStock',
        'available_from' => 'getAvailableFrom',
        'available_until' => 'getAvailableUntil',
        'branches' => 'getBranches',
        'product_reference' => 'getProductReference',
        'is_unlimited' => 'getIsUnlimited',
        'discount_type' => 'getDiscountType',
        'discount_value' => 'getDiscountValue',
        'max_redemptions_per_customer' => 'getMaxRedemptionsPerCustomer',
        'customer_redemptions' => 'getCustomerRedemptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DISCOUNT_TYPE_FIXED_AMOUNT = 'fixed_amount';
    public const DISCOUNT_TYPE_PERCENTAGE = 'percentage';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDiscountTypeAllowableValues()
    {
        return [
            self::DISCOUNT_TYPE_FIXED_AMOUNT,
            self::DISCOUNT_TYPE_PERCENTAGE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('point_cost', $data ?? [], null);
        $this->setIfExists('payment_amount', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('remaining_stock', $data ?? [], null);
        $this->setIfExists('total_stock', $data ?? [], null);
        $this->setIfExists('available_from', $data ?? [], null);
        $this->setIfExists('available_until', $data ?? [], null);
        $this->setIfExists('branches', $data ?? [], null);
        $this->setIfExists('product_reference', $data ?? [], null);
        $this->setIfExists('is_unlimited', $data ?? [], null);
        $this->setIfExists('discount_type', $data ?? [], null);
        $this->setIfExists('discount_value', $data ?? [], null);
        $this->setIfExists('max_redemptions_per_customer', $data ?? [], null);
        $this->setIfExists('customer_redemptions', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['description'] === null && !$this->isNullableSetToNull('description')) {
            $invalidProperties[] = "'description' is required";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['point_cost'] === null) {
            $invalidProperties[] = "'point_cost' can't be null";
        }
        if ($this->container['payment_amount'] === null) {
            $invalidProperties[] = "'payment_amount' can't be null";
        }
        if ($this->container['image_url'] === null && !$this->isNullableSetToNull('image_url')) {
            $invalidProperties[] = "'image_url' is required";
        }
        if ($this->container['remaining_stock'] === null && !$this->isNullableSetToNull('remaining_stock')) {
            $invalidProperties[] = "'remaining_stock' is required";
        }
        if ($this->container['total_stock'] === null && !$this->isNullableSetToNull('total_stock')) {
            $invalidProperties[] = "'total_stock' is required";
        }
        if ($this->container['available_from'] === null && !$this->isNullableSetToNull('available_from')) {
            $invalidProperties[] = "'available_from' is required";
        }
        if ($this->container['available_until'] === null && !$this->isNullableSetToNull('available_until')) {
            $invalidProperties[] = "'available_until' is required";
        }
        if ($this->container['branches'] === null && !$this->isNullableSetToNull('branches')) {
            $invalidProperties[] = "'branches' is required";
        }
        if ($this->container['product_reference'] === null && !$this->isNullableSetToNull('product_reference')) {
            $invalidProperties[] = "'product_reference' is required";
        }
        if ($this->container['is_unlimited'] === null) {
            $invalidProperties[] = "'is_unlimited' can't be null";
        }
        if ($this->container['discount_type'] === null && !$this->isNullableSetToNull('discount_type')) {
            $invalidProperties[] = "'discount_type' is required";
        }
        $allowedValues = $this->getDiscountTypeAllowableValues();
        if (!is_null($this->container['discount_type']) && !in_array($this->container['discount_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'discount_type', must be one of '%s'",
                $this->container['discount_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['discount_value'] === null && !$this->isNullableSetToNull('discount_value')) {
            $invalidProperties[] = "'discount_value' is required";
        }
        if ($this->container['max_redemptions_per_customer'] === null && !$this->isNullableSetToNull('max_redemptions_per_customer')) {
            $invalidProperties[] = "'max_redemptions_per_customer' is required";
        }
        if ($this->container['customer_redemptions'] === null && !$this->isNullableSetToNull('customer_redemptions')) {
            $invalidProperties[] = "'customer_redemptions' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets point_cost
     *
     * @return int
     */
    public function getPointCost()
    {
        return $this->container['point_cost'];
    }

    /**
     * Sets point_cost
     *
     * @param int $point_cost point_cost
     *
     * @return self
     */
    public function setPointCost($point_cost)
    {
        if (is_null($point_cost)) {
            throw new \InvalidArgumentException('non-nullable point_cost cannot be null');
        }
        $this->container['point_cost'] = $point_cost;

        return $this;
    }

    /**
     * Gets payment_amount
     *
     * @return int
     */
    public function getPaymentAmount()
    {
        return $this->container['payment_amount'];
    }

    /**
     * Sets payment_amount
     *
     * @param int $payment_amount payment_amount
     *
     * @return self
     */
    public function setPaymentAmount($payment_amount)
    {
        if (is_null($payment_amount)) {
            throw new \InvalidArgumentException('non-nullable payment_amount cannot be null');
        }
        $this->container['payment_amount'] = $payment_amount;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            array_push($this->openAPINullablesSetToNull, 'image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets remaining_stock
     *
     * @return int|null
     */
    public function getRemainingStock()
    {
        return $this->container['remaining_stock'];
    }

    /**
     * Sets remaining_stock
     *
     * @param int|null $remaining_stock remaining_stock
     *
     * @return self
     */
    public function setRemainingStock($remaining_stock)
    {
        if (is_null($remaining_stock)) {
            array_push($this->openAPINullablesSetToNull, 'remaining_stock');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('remaining_stock', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['remaining_stock'] = $remaining_stock;

        return $this;
    }

    /**
     * Gets total_stock
     *
     * @return int|null
     */
    public function getTotalStock()
    {
        return $this->container['total_stock'];
    }

    /**
     * Sets total_stock
     *
     * @param int|null $total_stock total_stock
     *
     * @return self
     */
    public function setTotalStock($total_stock)
    {
        if (is_null($total_stock)) {
            array_push($this->openAPINullablesSetToNull, 'total_stock');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('total_stock', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['total_stock'] = $total_stock;

        return $this;
    }

    /**
     * Gets available_from
     *
     * @return string|null
     */
    public function getAvailableFrom()
    {
        return $this->container['available_from'];
    }

    /**
     * Sets available_from
     *
     * @param string|null $available_from available_from
     *
     * @return self
     */
    public function setAvailableFrom($available_from)
    {
        if (is_null($available_from)) {
            array_push($this->openAPINullablesSetToNull, 'available_from');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('available_from', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['available_from'] = $available_from;

        return $this;
    }

    /**
     * Gets available_until
     *
     * @return string|null
     */
    public function getAvailableUntil()
    {
        return $this->container['available_until'];
    }

    /**
     * Sets available_until
     *
     * @param string|null $available_until available_until
     *
     * @return self
     */
    public function setAvailableUntil($available_until)
    {
        if (is_null($available_until)) {
            array_push($this->openAPINullablesSetToNull, 'available_until');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('available_until', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['available_until'] = $available_until;

        return $this;
    }

    /**
     * Gets branches
     *
     * @return \Puntjes\Spike\Oag\Model\BranchReferenceData[]|null
     */
    public function getBranches()
    {
        return $this->container['branches'];
    }

    /**
     * Sets branches
     *
     * @param \Puntjes\Spike\Oag\Model\BranchReferenceData[]|null $branches null means every branch
     *
     * @return self
     */
    public function setBranches($branches)
    {
        if (is_null($branches)) {
            array_push($this->openAPINullablesSetToNull, 'branches');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('branches', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['branches'] = $branches;

        return $this;
    }

    /**
     * Gets product_reference
     *
     * @return string|null
     */
    public function getProductReference()
    {
        return $this->container['product_reference'];
    }

    /**
     * Sets product_reference
     *
     * @param string|null $product_reference The item number the reward is for. Read type first: null is the whole purchase for a discount, no item number for a free product.
     *
     * @return self
     */
    public function setProductReference($product_reference)
    {
        if (is_null($product_reference)) {
            array_push($this->openAPINullablesSetToNull, 'product_reference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('product_reference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['product_reference'] = $product_reference;

        return $this;
    }

    /**
     * Gets is_unlimited
     *
     * @return bool
     */
    public function getIsUnlimited()
    {
        return $this->container['is_unlimited'];
    }

    /**
     * Sets is_unlimited
     *
     * @param bool $is_unlimited True when the reward has no stock limit; remaining_stock is then 0.
     *
     * @return self
     */
    public function setIsUnlimited($is_unlimited)
    {
        if (is_null($is_unlimited)) {
            throw new \InvalidArgumentException('non-nullable is_unlimited cannot be null');
        }
        $this->container['is_unlimited'] = $is_unlimited;

        return $this;
    }

    /**
     * Gets discount_type
     *
     * @return string|null
     */
    public function getDiscountType()
    {
        return $this->container['discount_type'];
    }

    /**
     * Sets discount_type
     *
     * @param string|null $discount_type `percentage` or `fixed_amount` for a discount, null for a free product.
     *
     * @return self
     */
    public function setDiscountType($discount_type)
    {
        if (is_null($discount_type)) {
            array_push($this->openAPINullablesSetToNull, 'discount_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discount_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getDiscountTypeAllowableValues();
        if (!is_null($discount_type) && !in_array($discount_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'discount_type', must be one of '%s'",
                    $discount_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['discount_type'] = $discount_type;

        return $this;
    }

    /**
     * Gets discount_value
     *
     * @return int|null
     */
    public function getDiscountValue()
    {
        return $this->container['discount_value'];
    }

    /**
     * Sets discount_value
     *
     * @param int|null $discount_value A percentage as a whole number (10 is 10%), a fixed amount in cents; null for a free product.
     *
     * @return self
     */
    public function setDiscountValue($discount_value)
    {
        if (is_null($discount_value)) {
            array_push($this->openAPINullablesSetToNull, 'discount_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discount_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['discount_value'] = $discount_value;

        return $this;
    }

    /**
     * Gets max_redemptions_per_customer
     *
     * @return int|null
     */
    public function getMaxRedemptionsPerCustomer()
    {
        return $this->container['max_redemptions_per_customer'];
    }

    /**
     * Sets max_redemptions_per_customer
     *
     * @param int|null $max_redemptions_per_customer How many times one customer can redeem this reward; null means no limit.
     *
     * @return self
     */
    public function setMaxRedemptionsPerCustomer($max_redemptions_per_customer)
    {
        if (is_null($max_redemptions_per_customer)) {
            array_push($this->openAPINullablesSetToNull, 'max_redemptions_per_customer');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_redemptions_per_customer', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_redemptions_per_customer'] = $max_redemptions_per_customer;

        return $this;
    }

    /**
     * Gets customer_redemptions
     *
     * @return int|null
     */
    public function getCustomerRedemptions()
    {
        return $this->container['customer_redemptions'];
    }

    /**
     * Sets customer_redemptions
     *
     * @param int|null $customer_redemptions How many times the customer named by identifier redeemed this reward, cancelled ones left out; null when no identifier was sent or it matched nobody.
     *
     * @return self
     */
    public function setCustomerRedemptions($customer_redemptions)
    {
        if (is_null($customer_redemptions)) {
            array_push($this->openAPINullablesSetToNull, 'customer_redemptions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customer_redemptions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customer_redemptions'] = $customer_redemptions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


